config/routes.rb
Rails.application.routes.draw do
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/users/index' => 'users#index'
  get '/login' => 'users#login_form'
  post '/login' => 'users#login'
  
  get 'posts/index' => 'posts#index'
  get 'posts/new' => 'posts#new'
  get 'posts/:id' => 'posts#show'
  post 'posts/create' => 'posts#create'
  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/update' => 'posts#update', as: 'post_update'
  post 'posts/:id/delete' => 'posts#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(content: params[:content])
    if post.save
      flash[:notice] = "投稿に成功しました"
      redirect_to("/posts/index")
    end
  end

  def edit
     @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(content: params[:post][:content])
      flash[:notice] = "編集に成功しました"
    end
    redirect_to("/posts/index")
  end

  def delete
    post = Post.find_by(id: params[:id])
    if post.delete
      flash[:notice] = "削除に成功しました"
      redirect_to("/posts/index")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
    
  end

  def create
    user = User.new(name: params[:name], email: params[:email], password: params[:password])
    if  user.save
      flash[:notice] = "ユーザ登録に成功しました"
      redirect_to("/users/index")
    end
  end

  def login_form
    
  end

  def login
    user = User.find_by(email: params[:email])
    if user.password == params[:password]
      session[:user_id] = user.id
      flash[:notice] = "ログインに成功しました"
      redirect_to("/users/index")
    else
      flash[:notice] = "ログインに失敗しました"
      redirect_to("/login")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
	<footer class="l-content-expanded footer">
		<div class="l-content-fixed footer-content">
			<p class="footer-copy"><small>&copy; 2023 STON inc.</small></p>
			<p class="footer-totop" id="totop-btn"></p>
		</div>
	</footer>

app/views/layouts/_header.html.erb
  <header class="l-content-fixed header">
		<h1 class="header-logo">STON</h1>
		<nav class="nav">
			<ul class="nav-menu">
				<li class="nav-menu-item"><%= link_to("新規登録",signup_path)%></li>
				<li class="nav-menu-item"><%= link_to("ログイン",login_path)%></li>
				<li class="nav-menu-item"><%= link_to("投稿",posts_new_path)%></li>
				<li class="nav-menu-item"><a class="btn btn_highlighted btn_menuitem" href="contact.html">お問い合わせ</a></li>
			</ul>
		</nav>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StonRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="container">
      <%= render 'layouts/header'%>
        <% if flash[:notice]%>
          <%= flash[:notice]%>
        <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/posts/delete.html.erb
<h1>Post#delete</h1>
<p>Find me in app/views/post/delete.html.erb</p>

app/views/posts/edit.html.erb
<h1>編集画面</h1>
<div>
  <%= form_with model: @post, url: post_update_path(@post.id), method: :post do |f|%>
    <%= f.label "投稿内容"%>
    <%= f.text_field :content %>
    <%= f.submit "編集完了"%>
  <% end %>
</div>

app/views/posts/index.html.erb
<section class="l-content-fixed section">
			<header class="section-header">
				<h2 class="section-title">Posts</h2>
				<p class="section-subtitle">投稿一覧</p>
			</header>
			<div class="l-3column">
        <% @posts.each do |post|%>
				<article class="l-column">
						<a href="<%= "/posts#{post.id}"%>">
							<%= image_tag 'image-blog.png', class: "section-item-img" %>
							<p class="section-item-info-title">
								<time datetime="2018-09-04"><%= post.created_at%></time>EVENT
							</p>
							<h3 class="section-item-info">
								<%= link_to(post.content, "/posts/#{post.id}")%>
							</h3>
						</a>
				</article>
        <% end %>
			</div>
</section>

app/views/posts/new.html.erb
		<section class="l-content-fixed section">
			<header class="section-header">
				<h2 class="section-title">Content</h2>
				<p class="section-subtitle">新規投稿</p>
			</header>
      <div class="section-form">
        <%= form_with url: posts_create_path, class: "form-simple" do |f|%>
          <%= f.label "投稿内容", class: "form-label"%>
          <%= f.text_field :content, class: "form-input"%>
          <p class="form-btn-holder">
            <%= f.submit "保存する", class: "btn"%>
          </p>
        <% end %>
      </div>
		</section>

app/views/posts/show.html.erb
<h1>Post#show</h1>
<p><%= @post.content%></p>
<p><%= @post.id%></p>
<p><%= link_to("編集する", "/posts/#{@post.id}/edit")%></p>
<p><%= link_to("削除する", "/posts/#{@post.id}/delete", data: { "turbo-method": :post })%></p>

app/views/posts/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/login_form.html.erb
<section class="l-content-fixed section">
  <header class="section-header">
	<h2 class="section-title">ログイン</h2>
    <p class="section-subtitle">login</p>
  </header>
  <div class="section-form">
    <%= form_with url: "/login", class: "form-simple" do |f|%>
    <%= f.label "メールアドレス",  class: "form-label"%>
    <%= f.text_field :email, class: "form-input"%>
    <%= f.label "パスワード", class: "form-label"%>
    <%= f.text_field :password, class: "form-input"%>
    <p class="form-btn-holder">
      <%= f.submit "ログイン", class: "btn", data: { disable_with: "送信中..." }%>
    </p>
    <% end %>
  </div>
</section>

app/views/users/new.html.erb
<section class="l-content-fixed section">
  <header class="section-header">
	<h2 class="section-title">新規登録</h2>
    <p class="section-subtitle">SignUp</p>
  </header>
  <div class="section-form">
    <%= form_with url: "/signup", class: "form-simple" do |f|%>
    <%= f.label "名前",  class: "form-label"%>
    <%= f.text_field :name, class: "form-input"%>
    <%= f.label "メールアドレス",  class: "form-label"%>
    <%= f.text_field :email, class: "form-input"%>
    <%= f.label "パスワード", class: "form-label"%>
    <%= f.text_field :password, class: "form-input"%>
    <p class="form-btn-holder">
      <%= f.submit "保存する", class: "btn", data: { disable_with: "送信中..." }%>
    </p>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>